// Frozen A→B (indexer) / A→C (frontend) interface: contract ABIs + per-chain
// addresses generated by `scripts/gen-abis.mjs` from the compiled Foundry
// artifacts in `contracts/out/`. Do not hand-edit the abis/ or addresses/
// files this re-exports — re-run the generator instead.

import addresses4663 from "../addresses/4663.json" with { type: "json" };
import addresses46630 from "../addresses/46630.json" with { type: "json" };

export { launchFactoryAbi } from "../abis/LaunchFactory.ts";
export { tokenAbi } from "../abis/Token.ts";
export { lockerAbi } from "../abis/Locker.ts";
export { uniswapV3PoolAbi } from "../abis/UniswapV3Pool.ts";
export { uniswapV3FactoryAbi } from "../abis/UniswapV3Factory.ts";
export { swapRouter02Abi } from "../abis/SwapRouter02.ts";
export { erc20Abi } from "../abis/ERC20.ts";

/** Per-chain contract addresses: our own (deployed) contracts plus the DEX
 * venue this launchpad targets. `factory`/`locker` are `null` until a real
 * deploy has run (see `contracts/broadcast/Deploy.s.sol/<chainId>/run-latest.json`). */
export interface ChainAddresses {
  factory: string | null;
  locker: string | null;
  weth: string;
  uniswapV3Factory: string;
  positionManager: string;
  swapRouter: string;
}

/** Robinhood Chain mainnet (4663) and testnet (46630), keyed by chain id. */
export const addresses: Record<number, ChainAddresses> = {
  4663: addresses4663 as ChainAddresses,
  46630: addresses46630 as ChainAddresses,
};
