#!/usr/bin/env node
// Generates packages/shared/abis/*.ts and packages/shared/addresses/*.json from
// the compiled Foundry artifacts under contracts/out/. This is the frozen A→B
// (indexer) / A→C (frontend) interface — re-run after every contract change.
//
// Usage: node packages/shared/scripts/gen-abis.mjs
// Prerequisite: `forge build` must have populated contracts/out/.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SHARED_DIR = join(__dirname, "..");
const CONTRACTS_DIR = join(SHARED_DIR, "..", "..", "contracts");
const CONTRACTS_OUT = join(CONTRACTS_DIR, "out");
const CONTRACTS_BROADCAST = join(CONTRACTS_DIR, "broadcast");
// Output dirs default to the committed locations; the ABIS_OUT_DIR /
// ADDRESSES_OUT_DIR env overrides exist only so a test can drive the real
// generator into a scratch dir without touching (or racing readers of) the
// committed tree.
const ABIS_DIR = process.env.ABIS_OUT_DIR ? resolve(process.env.ABIS_OUT_DIR) : join(SHARED_DIR, "abis");
const ADDRESSES_DIR = process.env.ADDRESSES_OUT_DIR
  ? resolve(process.env.ADDRESSES_OUT_DIR)
  : join(SHARED_DIR, "addresses");

mkdirSync(ABIS_DIR, { recursive: true });
mkdirSync(ADDRESSES_DIR, { recursive: true });

/**
 * Reads a forge artifact's `.abi` and writes it to abis/<fileBaseName>.ts as
 * `export const <exportName> = [...] as const;`.
 */
function writeAbiFile(fileBaseName, exportName, abi) {
  const header =
    "// AUTO-GENERATED by packages/shared/scripts/gen-abis.mjs — do not edit by hand.\n";
  const body = `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(ABIS_DIR, `${fileBaseName}.ts`), header + body);
  console.log(`wrote abis/${fileBaseName}.ts (${exportName}, ${abi.length} entries)`);
}

function readForgeAbi(contractName, sourceFileName = `${contractName}.sol`) {
  const artifactPath = join(CONTRACTS_OUT, sourceFileName, `${contractName}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

// ---------------------------------------------------------------------------
// Step 1: our own contracts, compiled by forge build.
// ---------------------------------------------------------------------------

const OWN_CONTRACTS = [
  { contractName: "LaunchFactory", fileBaseName: "LaunchFactory", exportName: "launchFactoryAbi" },
  { contractName: "Token", fileBaseName: "Token", exportName: "tokenAbi" },
  { contractName: "Locker", fileBaseName: "Locker", exportName: "lockerAbi" },
];

for (const { contractName, fileBaseName, exportName } of OWN_CONTRACTS) {
  const abi = readForgeAbi(contractName);
  writeAbiFile(fileBaseName, exportName, abi);
}

// ---------------------------------------------------------------------------
// Step 2: external protocol fragments B indexes but that this repo does not
// compile a full interface for. Hand-written / extracted, kept minimal.
// ---------------------------------------------------------------------------

// Canonical Uniswap V3 pool `Swap` event (IUniswapV3PoolEvents). This repo's
// own `IUniswapV3Pool` interface (contracts/src/.../IUniswapV3.sol) is
// intentionally minimal (initialize/slot0/token0/token1 only) and does not
// declare this event, so it is hand-written here rather than extracted from a
// forge artifact.
const uniswapV3PoolAbi = [
  {
    type: "event",
    name: "Swap",
    inputs: [
      { name: "sender", type: "address", indexed: true, internalType: "address" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount0", type: "int256", indexed: false, internalType: "int256" },
      { name: "amount1", type: "int256", indexed: false, internalType: "int256" },
      { name: "sqrtPriceX96", type: "uint160", indexed: false, internalType: "uint160" },
      { name: "liquidity", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "tick", type: "int24", indexed: false, internalType: "int24" },
    ],
    anonymous: false,
  },
];
// --- uniswapV3PoolAbi: merge the compiled IUniswapV3Pool interface (slot0/
// token0/token1/initialize) with the hand-written Swap event above. Both are
// needed — B indexes Swap; C reads slot0 for live price. ---
const poolFunctionsAbi = readForgeAbi("IUniswapV3Pool", "IUniswapV3.sol");
const uniswapV3PoolAbiFull = [...poolFunctionsAbi, ...uniswapV3PoolAbi];
writeAbiFile("UniswapV3Pool", "uniswapV3PoolAbi", uniswapV3PoolAbiFull);

// --- uniswapV3FactoryAbi: getPool/createPool, compiled, used by C to derive a
// token's pool address (LaunchedToken doesn't carry it). ---
const uniswapV3FactoryAbi = readForgeAbi("IUniswapV3Factory", "IUniswapV3.sol");
writeAbiFile("UniswapV3Factory", "uniswapV3FactoryAbi", uniswapV3FactoryAbi);

// --- swapRouter02Abi: both exactInputSingle shapes come from the compiled
// ISwapRouter02 interface (it inherits IV3SwapRouter's no-deadline shape and
// ISwapRouter's with-deadline shape). multicall/unwrapWETH9 exist in NO
// compiled artifact in this repo (A's own contracts never call them — only
// the atomic dev-buy's plain exactInputSingle is used on the contract side),
// so they're hand-added here, matching the verified live-router shape
// already exercised in pons-launcher/backend/src/evm/abi.js.
const swapRouter02CompiledAbi = readForgeAbi("ISwapRouter02", "IUniswapV3.sol");
const swapRouter02Abi = [
  ...swapRouter02CompiledAbi,
  {
    type: "function",
    name: "multicall",
    inputs: [{ name: "data", type: "bytes[]", internalType: "bytes[]" }],
    outputs: [{ name: "results", type: "bytes[]", internalType: "bytes[]" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "unwrapWETH9",
    inputs: [
      { name: "amountMinimum", type: "uint256", internalType: "uint256" },
      { name: "recipient", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
];
writeAbiFile("SwapRouter02", "swapRouter02Abi", swapRouter02Abi);

// ERC-20 `Transfer` event, extracted verbatim from the compiled OpenZeppelin
// IERC20 artifact already in contracts/out/ so the fragment is guaranteed to
// match what Token.sol (and any other ERC-20) actually emits.
const ierc20Abi = readForgeAbi("IERC20");
const transferEvent = ierc20Abi.find((entry) => entry.type === "event" && entry.name === "Transfer");
if (!transferEvent) {
  throw new Error("gen-abis: could not find Transfer event in contracts/out/IERC20.sol/IERC20.json");
}
writeAbiFile("ERC20", "erc20Abi", [transferEvent]);

// ---------------------------------------------------------------------------
// Step 3: per-chain addresses. The DEX addresses are the live Robinhood Chain
// (4663) Uniswap-V3-shaped venue; no separate testnet (46630) DEX deployment is
// documented anywhere in this repo, so the same values are used there too
// until/unless testnet-specific addresses are confirmed.
//
// Our own factory/locker are NEVER promoted from the broadcast log by default.
// A routine `forge build` + `pnpm gen-abis` after a LOCAL-FORK rehearsal leaves
// a real-looking `broadcast/Deploy.s.sol/4663/run-latest.json` (chain 4663 is
// the real mainnet id, deployer = an Anvil default), and silently promoting it
// would flip the committed `addresses/4663.json` factory/locker from their
// correct `null` placeholders to throwaway fork addresses — a poisoned address
// file that, if committed and deployed, points B/C at a dead address. So:
//
//   * Default: regenerate the ABIs, but leave `addresses/<chainId>.json`
//     UNCHANGED — the committed factory/locker values are preserved verbatim.
//   * Opt-in (`PROMOTE_DEPLOY_ADDRESSES=1`): read the broadcast log and update
//     factory/locker — but REFUSE to promote for a non-testnet chain id when the
//     broadcast deployer (tx `from`) is a known Anvil/Foundry default account.
// ---------------------------------------------------------------------------

const DEX_ADDRESSES = {
  weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
  uniswapV3Factory: "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA",
  positionManager: "0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3",
  swapRouter: "0xCaf681a66D020601342297493863E78C959E5cb2",
};

const CHAIN_IDS = [4663, 46630];

// Chain ids that are safe to auto-promote a fork/default-deployer broadcast for
// (a testnet id is throwaway by nature). Everything else is treated as a
// production id where an Anvil-default deployer signals a fork rehearsal.
const TESTNET_CHAIN_IDS = new Set([46630]);

// The standard Foundry/Anvil default accounts, derived from the well-known test
// mnemonic ("test test test test test test test test test test test junk").
// A broadcast whose deployer is one of these on a NON-testnet chain is a local
// fork rehearsal, never a real deploy — refuse to promote its addresses.
const ANVIL_DEFAULT_ACCOUNTS = new Set(
  [
    "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
    "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
    "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC",
    "0x90F79bf6EB2c4f870365E785982E1f101E93b906",
    "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65",
    "0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc",
    "0x976EA74026E726554dB657fA54763abd0C3a0aa9",
    "0x14dC79964da2C08b23698B3D3cc7Ca32193d9955",
    "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f",
    "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720",
  ].map((a) => a.toLowerCase()),
);

const PROMOTE = process.env.PROMOTE_DEPLOY_ADDRESSES === "1";

/** Reads the committed `addresses/<chainId>.json` (if any) so a default run can
 * preserve its factory/locker verbatim. Returns `{ factory: null, locker: null }`
 * when the file is absent or unparseable. */
function readCommittedAddresses(chainId) {
  const path = join(ADDRESSES_DIR, `${chainId}.json`);
  if (!existsSync(path)) return { factory: null, locker: null };
  try {
    const current = JSON.parse(readFileSync(path, "utf8"));
    return { factory: current.factory ?? null, locker: current.locker ?? null };
  } catch {
    return { factory: null, locker: null };
  }
}

/**
 * Reads contracts/broadcast/Deploy.s.sol/<chainId>/run-latest.json (if it
 * exists) and pulls out the deployed LaunchFactory/Locker CREATE addresses plus
 * the deployer (the CREATE tx's `from`). Returns nulls when no deploy has
 * happened yet, or when the file exists but can't be parsed as expected (fails
 * soft: this script should never hard-fail just because a deploy log is
 * malformed).
 */
function readDeployedAddresses(chainId) {
  const runPath = join(CONTRACTS_BROADCAST, "Deploy.s.sol", String(chainId), "run-latest.json");
  if (!existsSync(runPath)) {
    return { factory: null, locker: null, deployer: null };
  }
  try {
    const run = JSON.parse(readFileSync(runPath, "utf8"));
    const transactions = run.transactions ?? [];
    const factoryTx = transactions.find(
      (tx) => tx.transactionType === "CREATE" && tx.contractName === "LaunchFactory",
    );
    const lockerTx = transactions.find(
      (tx) => tx.transactionType === "CREATE" && tx.contractName === "Locker",
    );
    // Foundry nests the signer under `.transaction.from`; tolerate a top-level
    // `.from` too in case a future broadcast schema flattens it.
    const deployer =
      factoryTx?.transaction?.from ?? factoryTx?.from ?? lockerTx?.transaction?.from ?? lockerTx?.from ?? null;
    return {
      factory: factoryTx?.contractAddress ?? null,
      locker: lockerTx?.contractAddress ?? null,
      deployer,
    };
  } catch (err) {
    console.warn(`warning: found ${runPath} but failed to parse it (${err.message}); leaving addresses unchanged`);
    return { factory: null, locker: null, deployer: null };
  }
}

/**
 * Resolves the factory/locker to write for a chain. Default: the committed
 * values, untouched. Promote mode: the broadcast values, unless the chain is a
 * production id deployed by an Anvil default account (a fork rehearsal), in
 * which case it refuses and keeps the committed values.
 */
function resolveOwnAddresses(chainId) {
  const committed = readCommittedAddresses(chainId);
  if (!PROMOTE) {
    return committed;
  }
  const deployed = readDeployedAddresses(chainId);
  if (deployed.factory === null && deployed.locker === null) {
    console.log(
      `addresses/${chainId}.json: PROMOTE set but no broadcast log found — keeping committed factory/locker.`,
    );
    return committed;
  }
  const deployer = deployed.deployer ? String(deployed.deployer).toLowerCase() : null;
  const isDefaultDeployer = deployer !== null && ANVIL_DEFAULT_ACCOUNTS.has(deployer);
  if (isDefaultDeployer && !TESTNET_CHAIN_IDS.has(chainId)) {
    console.warn(
      `addresses/${chainId}.json: REFUSING to promote — broadcast deployer ${deployed.deployer} is a known ` +
        `Anvil/Foundry default account on a non-testnet chain (looks like a local-fork rehearsal). ` +
        `Committed factory/locker preserved.`,
    );
    return committed;
  }
  console.log(
    `addresses/${chainId}.json: promoting broadcast addresses (deployer=${deployed.deployer ?? "unknown"}).`,
  );
  return { factory: deployed.factory, locker: deployed.locker };
}

for (const chainId of CHAIN_IDS) {
  const own = resolveOwnAddresses(chainId);
  const addresses = {
    factory: own.factory,
    locker: own.locker,
    ...DEX_ADDRESSES,
  };
  writeFileSync(join(ADDRESSES_DIR, `${chainId}.json`), `${JSON.stringify(addresses, null, 2)}\n`);
  console.log(
    `wrote addresses/${chainId}.json (factory=${addresses.factory ?? "null"}, locker=${addresses.locker ?? "null"})`,
  );
}
