#!/usr/bin/env node
// Generates packages/shared/abis/*.ts and packages/shared/addresses/*.json from
// the compiled Foundry artifacts under contracts/out/. This is the frozen A→B
// (indexer) / A→C (frontend) interface — re-run after every contract change.
//
// Usage: node packages/shared/scripts/gen-abis.mjs
// Prerequisite: `forge build` must have populated contracts/out/.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SHARED_DIR = join(__dirname, "..");
const CONTRACTS_DIR = join(SHARED_DIR, "..", "..", "contracts");
const CONTRACTS_OUT = join(CONTRACTS_DIR, "out");
const CONTRACTS_BROADCAST = join(CONTRACTS_DIR, "broadcast");
const ABIS_DIR = join(SHARED_DIR, "abis");
const ADDRESSES_DIR = join(SHARED_DIR, "addresses");

mkdirSync(ABIS_DIR, { recursive: true });
mkdirSync(ADDRESSES_DIR, { recursive: true });

/**
 * Reads a forge artifact's `.abi` and writes it to abis/<fileBaseName>.ts as
 * `export const <exportName> = [...] as const;`.
 */
function writeAbiFile(fileBaseName, exportName, abi) {
  const header =
    "// AUTO-GENERATED by packages/shared/scripts/gen-abis.mjs — do not edit by hand.\n";
  const body = `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(ABIS_DIR, `${fileBaseName}.ts`), header + body);
  console.log(`wrote abis/${fileBaseName}.ts (${exportName}, ${abi.length} entries)`);
}

function readForgeAbi(contractName) {
  const artifactPath = join(CONTRACTS_OUT, `${contractName}.sol`, `${contractName}.json`);
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

// ---------------------------------------------------------------------------
// Step 1: our own contracts, compiled by forge build.
// ---------------------------------------------------------------------------

const OWN_CONTRACTS = [
  { contractName: "LaunchFactory", fileBaseName: "LaunchFactory", exportName: "launchFactoryAbi" },
  { contractName: "Token", fileBaseName: "Token", exportName: "tokenAbi" },
  { contractName: "Locker", fileBaseName: "Locker", exportName: "lockerAbi" },
];

for (const { contractName, fileBaseName, exportName } of OWN_CONTRACTS) {
  const abi = readForgeAbi(contractName);
  writeAbiFile(fileBaseName, exportName, abi);
}

// ---------------------------------------------------------------------------
// Step 2: external protocol fragments B indexes but that this repo does not
// compile a full interface for. Hand-written / extracted, kept minimal.
// ---------------------------------------------------------------------------

// Canonical Uniswap V3 pool `Swap` event (IUniswapV3PoolEvents). This repo's
// own `IUniswapV3Pool` interface (contracts/src/.../IUniswapV3.sol) is
// intentionally minimal (initialize/slot0/token0/token1 only) and does not
// declare this event, so it is hand-written here rather than extracted from a
// forge artifact.
const uniswapV3PoolAbi = [
  {
    type: "event",
    name: "Swap",
    inputs: [
      { name: "sender", type: "address", indexed: true, internalType: "address" },
      { name: "recipient", type: "address", indexed: true, internalType: "address" },
      { name: "amount0", type: "int256", indexed: false, internalType: "int256" },
      { name: "amount1", type: "int256", indexed: false, internalType: "int256" },
      { name: "sqrtPriceX96", type: "uint160", indexed: false, internalType: "uint160" },
      { name: "liquidity", type: "uint128", indexed: false, internalType: "uint128" },
      { name: "tick", type: "int24", indexed: false, internalType: "int24" },
    ],
    anonymous: false,
  },
];
writeAbiFile("UniswapV3Pool", "uniswapV3PoolAbi", uniswapV3PoolAbi);

// ERC-20 `Transfer` event, extracted verbatim from the compiled OpenZeppelin
// IERC20 artifact already in contracts/out/ so the fragment is guaranteed to
// match what Token.sol (and any other ERC-20) actually emits.
const ierc20Abi = readForgeAbi("IERC20");
const transferEvent = ierc20Abi.find((entry) => entry.type === "event" && entry.name === "Transfer");
if (!transferEvent) {
  throw new Error("gen-abis: could not find Transfer event in contracts/out/IERC20.sol/IERC20.json");
}
writeAbiFile("ERC20", "erc20Abi", [transferEvent]);

// ---------------------------------------------------------------------------
// Step 3: per-chain addresses. Our own factory/locker are read from the
// broadcast run log when a real deploy has happened; otherwise they are
// `null` placeholders. The DEX addresses are the live Robinhood Chain (4663)
// Uniswap-V3-shaped venue; no separate testnet (46630) DEX deployment is
// documented anywhere in this repo, so the same values are used there too
// until/unless testnet-specific addresses are confirmed.
// ---------------------------------------------------------------------------

const DEX_ADDRESSES = {
  weth: "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73",
  uniswapV3Factory: "0x1f7d7550B1b028f7571E69A784071F0205FD2EfA",
  positionManager: "0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3",
  swapRouter: "0xCaf681a66D020601342297493863E78C959E5cb2",
};

const CHAIN_IDS = [4663, 46630];

/**
 * Reads contracts/broadcast/Deploy.s.sol/<chainId>/run-latest.json (if it
 * exists) and pulls out the deployed LaunchFactory/Locker CREATE addresses.
 * Returns { factory: null, locker: null } when no deploy has happened yet, or
 * when the file exists but can't be parsed as expected (fails soft: this
 * script should never hard-fail just because a deploy log is malformed).
 */
function readDeployedAddresses(chainId) {
  const runPath = join(CONTRACTS_BROADCAST, "Deploy.s.sol", String(chainId), "run-latest.json");
  if (!existsSync(runPath)) {
    return { factory: null, locker: null };
  }
  try {
    const run = JSON.parse(readFileSync(runPath, "utf8"));
    const transactions = run.transactions ?? [];
    const factoryTx = transactions.find(
      (tx) => tx.transactionType === "CREATE" && tx.contractName === "LaunchFactory",
    );
    const lockerTx = transactions.find(
      (tx) => tx.transactionType === "CREATE" && tx.contractName === "Locker",
    );
    return {
      factory: factoryTx?.contractAddress ?? null,
      locker: lockerTx?.contractAddress ?? null,
    };
  } catch (err) {
    console.warn(`warning: found ${runPath} but failed to parse it (${err.message}); using null placeholders`);
    return { factory: null, locker: null };
  }
}

for (const chainId of CHAIN_IDS) {
  const deployed = readDeployedAddresses(chainId);
  const addresses = {
    factory: deployed.factory,
    locker: deployed.locker,
    ...DEX_ADDRESSES,
  };
  writeFileSync(join(ADDRESSES_DIR, `${chainId}.json`), `${JSON.stringify(addresses, null, 2)}\n`);
  console.log(
    `wrote addresses/${chainId}.json (factory=${addresses.factory ?? "null"}, locker=${addresses.locker ?? "null"})`,
  );
}
